theme: jekyll-theme-tactile
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - PRIVACY_POLICY.md
  - README.md
title: uFinance
description: Upgrade your Yahoo Finance experience!
